/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tdd1;

public class App {
    public String getGreeting() {
        return "世界よこんにちは!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    public Integer addOne(int i) {
        return 0; // エラー発生
    }
}
