/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tdd1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    // 佐藤が追加したものです
    @Test void canAddOne() {
        App classUnderTest = new App();
        assertEquals(42, classUnderTest.addOne(41),"41+1=42");
    }
}
